name: local_notifications
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: 0.27.5
  path_provider: 2.0.4
  http: 0.13.1
  flutter_local_notifications: ^9.0.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true